[build]
  command = "bash ./netlify-build.sh"
  publish = "dist"
  base = "."

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps"

# This ensures that all routes are handled properly
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Handle 404 errors
[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404