[build]
  publish = "dist"
  command = "node memory-monitor.js && node netlify-bootstrap.js"
  
[build.environment]
  NODE_VERSION = "16"
  NODE_OPTIONS = "--max-old-space-size=2048 --no-warnings --max-http-header-size=16384"
  ASTRO_MEMORY_LIMIT = "true"
  VITE_MEMORY_LIMIT = "true"
  NPM_FLAGS = "--no-fund --no-audit --no-optional --prefer-offline --loglevel=error"
  
# Fallback build approach if the main build fails
[context.deploy-fallback]
  command = "npm run minimal-build"

# Redirect to handle SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false
  conditions = {Role = ["admin"]}

# Enable brotli compression
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Content-Security-Policy = "frame-ancestors 'none'"

# Set cache headers for static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.webp"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Handle 404 errors
[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404