[build]
  command = "node copy-package.js && node netlify.js && npm run build"
  publish = "dist"
  base = "."

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--no-audit --prefer-offline"
  NETLIFY_USE_YARN = "false"
  CI = "true"

# This ensures that all routes are handled properly
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Handle 404 errors
[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404