[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

# This ensures that all routes are handled properly
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200