[build]
  command = "node netlify-bootstrap.cjs"
  publish = "dist"
  base = "playable-data-blog"

[build.environment]
  # Node.js configuration
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps --no-warnings"
  
  # Use a valid Ruby version instead of trying to disable it
  RUBY_VERSION = "2.7.2"
  
  # Python configuration - use a version definitely available in Netlify
  PYTHON_VERSION = "3.8" 
  PIP_DISABLE_PIP_VERSION_CHECK = "1"
  
  # Force Netlify to detect this as a Node.js project
  NETLIFY_EXPERIMENTAL_BUILD_NODEJS_ONLY = "true"
  
  # Disable mise's auto version resolution to prevent version confusion
  MISE_PYTHON_DISABLE_AUTO = "true"
  
  # Prevent npm warnings from breaking the build
  CI = "false"
  
  # Npm warning ignoring
  npm_config_loglevel = "error"

# This ensures that all routes are handled properly
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Handle 404 errors
[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404